apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  labels:
    managed-by: dso
spec:
  replicas: 3
  selector:
    matchLabels:
      application: my-jenkins
  template:
    metadata:
      labels:
        application: my-jenkins
    spec:
      serviceAccountName: my-jenkins-sa
      containers:
        - name: my-jenkins
          image: jenkins/jenkins
          ports:
            - name: http
              containerPort: 80