apiVersion: v1
kind: Service
metadata:
  name: my-jenkins-svc
  labels:
    managed-by: dso
spec:
  selector:
    application: my-jenkins
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http